# Generated by Django 5.2.5 on 2026-07-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'permissions': [('can_process_payment', 'Can process a payment via /pay')]},
        ),
    ]
