# Generated by Django 5.2.5 on 2026-07-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
